Corrections
nxengine/lang_french pull request #3
Opened 2024-04-30 11:15 UTC by Cwpute

various corrections and translation changes

2024-04-30 11:17 UTC, Cwpute commented
permet de fermer #2

2024-05-01 07:53 UTC, jmfergeau requested changes
Les lignes 136 et 137 devraient être sur une seule ligne comme ceci : `aux Mimigas enragés ?<NOD<CLR.....<NOD<CLRC'est une triste` sinon la text box risque de faire un retour de ligne inutile qui peut cacher du texte :p

2024-05-01 10:36 UTC, Cwpute commented
Corrigé.
J'avoues ne pas avoir cherché comment les lignes sont gérées par le jeu, j'ai extrapolé en regardant comment les autres lignes étaient gérées dans le code. Pourquoi ça n'aurait pas marché ici ?

2024-05-01 19:43 UTC, jmfergeau approved these changes

2024-05-01 19:44 UTC, merged

2024-05-01 19:44 UTC, jmfergeau commented
ça aurait marché mais ça aurait causé un espace inutile qui pourrait cacher du texte. :p